/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PersonalDetailsImport } from './routes/personal-details'
import { Route as OrdersImport } from './routes/orders'
import { Route as NewAddressImport } from './routes/new-address'
import { Route as MenuImport } from './routes/menu'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as CartImport } from './routes/cart'
import { Route as AddressesImport } from './routes/addresses'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as OrdersOrderIdImport } from './routes/orders.$orderId'
import { Route as CartCheckoutImport } from './routes/cart.checkout'
import { Route as AuthSignInImport } from './routes/auth.sign-in'
import { Route as AuthRegisterImport } from './routes/auth.register'
import { Route as AddressesNewImport } from './routes/addresses.new'
import { Route as MenuProductProductIdImport } from './routes/menu.product.$productId'
import { Route as MenuCategoryAllImport } from './routes/menu.category.all'
import { Route as MenuCategoryCategoryIdImport } from './routes/menu.category.$categoryId'

// Create/Update Routes

const PersonalDetailsRoute = PersonalDetailsImport.update({
  id: '/personal-details',
  path: '/personal-details',
  getParentRoute: () => rootRoute,
} as any)

const OrdersRoute = OrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any)

const NewAddressRoute = NewAddressImport.update({
  id: '/new-address',
  path: '/new-address',
  getParentRoute: () => rootRoute,
} as any)

const MenuRoute = MenuImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRoute = CheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AddressesRoute = AddressesImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrdersOrderIdRoute = OrdersOrderIdImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)

const CartCheckoutRoute = CartCheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CartRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AddressesNewRoute = AddressesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AddressesRoute,
} as any)

const MenuProductProductIdRoute = MenuProductProductIdImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => MenuRoute,
} as any)

const MenuCategoryAllRoute = MenuCategoryAllImport.update({
  id: '/category/all',
  path: '/category/all',
  getParentRoute: () => MenuRoute,
} as any)

const MenuCategoryCategoryIdRoute = MenuCategoryCategoryIdImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => MenuRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuImport
      parentRoute: typeof rootRoute
    }
    '/new-address': {
      id: '/new-address'
      path: '/new-address'
      fullPath: '/new-address'
      preLoaderRoute: typeof NewAddressImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
    '/personal-details': {
      id: '/personal-details'
      path: '/personal-details'
      fullPath: '/personal-details'
      preLoaderRoute: typeof PersonalDetailsImport
      parentRoute: typeof rootRoute
    }
    '/addresses/new': {
      id: '/addresses/new'
      path: '/new'
      fullPath: '/addresses/new'
      preLoaderRoute: typeof AddressesNewImport
      parentRoute: typeof AddressesImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/cart/checkout': {
      id: '/cart/checkout'
      path: '/checkout'
      fullPath: '/cart/checkout'
      preLoaderRoute: typeof CartCheckoutImport
      parentRoute: typeof CartImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdImport
      parentRoute: typeof OrdersImport
    }
    '/menu/category/$categoryId': {
      id: '/menu/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/menu/category/$categoryId'
      preLoaderRoute: typeof MenuCategoryCategoryIdImport
      parentRoute: typeof MenuImport
    }
    '/menu/category/all': {
      id: '/menu/category/all'
      path: '/category/all'
      fullPath: '/menu/category/all'
      preLoaderRoute: typeof MenuCategoryAllImport
      parentRoute: typeof MenuImport
    }
    '/menu/product/$productId': {
      id: '/menu/product/$productId'
      path: '/product/$productId'
      fullPath: '/menu/product/$productId'
      preLoaderRoute: typeof MenuProductProductIdImport
      parentRoute: typeof MenuImport
    }
  }
}

// Create and export the route tree

interface AddressesRouteChildren {
  AddressesNewRoute: typeof AddressesNewRoute
}

const AddressesRouteChildren: AddressesRouteChildren = {
  AddressesNewRoute: AddressesNewRoute,
}

const AddressesRouteWithChildren = AddressesRoute._addFileChildren(
  AddressesRouteChildren,
)

interface CartRouteChildren {
  CartCheckoutRoute: typeof CartCheckoutRoute
}

const CartRouteChildren: CartRouteChildren = {
  CartCheckoutRoute: CartCheckoutRoute,
}

const CartRouteWithChildren = CartRoute._addFileChildren(CartRouteChildren)

interface MenuRouteChildren {
  MenuCategoryCategoryIdRoute: typeof MenuCategoryCategoryIdRoute
  MenuCategoryAllRoute: typeof MenuCategoryAllRoute
  MenuProductProductIdRoute: typeof MenuProductProductIdRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuCategoryCategoryIdRoute: MenuCategoryCategoryIdRoute,
  MenuCategoryAllRoute: MenuCategoryAllRoute,
  MenuProductProductIdRoute: MenuProductProductIdRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRouteWithChildren
  '/new-address': typeof NewAddressRoute
  '/orders': typeof OrdersRouteWithChildren
  '/personal-details': typeof PersonalDetailsRoute
  '/addresses/new': typeof AddressesNewRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/menu/category/$categoryId': typeof MenuCategoryCategoryIdRoute
  '/menu/category/all': typeof MenuCategoryAllRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRouteWithChildren
  '/new-address': typeof NewAddressRoute
  '/orders': typeof OrdersRouteWithChildren
  '/personal-details': typeof PersonalDetailsRoute
  '/addresses/new': typeof AddressesNewRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/menu/category/$categoryId': typeof MenuCategoryCategoryIdRoute
  '/menu/category/all': typeof MenuCategoryAllRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/cart': typeof CartRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRouteWithChildren
  '/new-address': typeof NewAddressRoute
  '/orders': typeof OrdersRouteWithChildren
  '/personal-details': typeof PersonalDetailsRoute
  '/addresses/new': typeof AddressesNewRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/menu/category/$categoryId': typeof MenuCategoryCategoryIdRoute
  '/menu/category/all': typeof MenuCategoryAllRoute
  '/menu/product/$productId': typeof MenuProductProductIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/new-address'
    | '/orders'
    | '/personal-details'
    | '/addresses/new'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cart/checkout'
    | '/orders/$orderId'
    | '/menu/category/$categoryId'
    | '/menu/category/all'
    | '/menu/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/new-address'
    | '/orders'
    | '/personal-details'
    | '/addresses/new'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cart/checkout'
    | '/orders/$orderId'
    | '/menu/category/$categoryId'
    | '/menu/category/all'
    | '/menu/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/new-address'
    | '/orders'
    | '/personal-details'
    | '/addresses/new'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cart/checkout'
    | '/orders/$orderId'
    | '/menu/category/$categoryId'
    | '/menu/category/all'
    | '/menu/product/$productId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddressesRoute: typeof AddressesRouteWithChildren
  CartRoute: typeof CartRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRouteWithChildren
  NewAddressRoute: typeof NewAddressRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PersonalDetailsRoute: typeof PersonalDetailsRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddressesRoute: AddressesRouteWithChildren,
  CartRoute: CartRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRouteWithChildren,
  NewAddressRoute: NewAddressRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PersonalDetailsRoute: PersonalDetailsRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/addresses",
        "/cart",
        "/checkout",
        "/menu",
        "/new-address",
        "/orders",
        "/personal-details",
        "/auth/register",
        "/auth/sign-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/addresses": {
      "filePath": "addresses.tsx",
      "children": [
        "/addresses/new"
      ]
    },
    "/cart": {
      "filePath": "cart.tsx",
      "children": [
        "/cart/checkout"
      ]
    },
    "/checkout": {
      "filePath": "checkout.tsx"
    },
    "/menu": {
      "filePath": "menu.tsx",
      "children": [
        "/menu/category/$categoryId",
        "/menu/category/all",
        "/menu/product/$productId"
      ]
    },
    "/new-address": {
      "filePath": "new-address.tsx"
    },
    "/orders": {
      "filePath": "orders.tsx",
      "children": [
        "/orders/$orderId"
      ]
    },
    "/personal-details": {
      "filePath": "personal-details.tsx"
    },
    "/addresses/new": {
      "filePath": "addresses.new.tsx",
      "parent": "/addresses"
    },
    "/auth/register": {
      "filePath": "auth.register.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth.sign-in.tsx"
    },
    "/cart/checkout": {
      "filePath": "cart.checkout.tsx",
      "parent": "/cart"
    },
    "/orders/$orderId": {
      "filePath": "orders.$orderId.tsx",
      "parent": "/orders"
    },
    "/menu/category/$categoryId": {
      "filePath": "menu.category.$categoryId.tsx",
      "parent": "/menu"
    },
    "/menu/category/all": {
      "filePath": "menu.category.all.tsx",
      "parent": "/menu"
    },
    "/menu/product/$productId": {
      "filePath": "menu.product.$productId.tsx",
      "parent": "/menu"
    }
  }
}
ROUTE_MANIFEST_END */
